PROJ=main
FILES= main.c scanner.c parser.c symtable.c code_generator.c dstring.c prec_analysis.c psa_stack.c
HEADS= scanner.h error.h symtable.h code_generator.h dstring.h prec_analysis.h psa_stack.h
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic -pthread
CC=gcc
RM=rm -f

all : $(PROJ)

$(PROJ) : $(FILES)
		$(CC) $(CFLAGS) -o $(PROJ) $(FILES) -lm

clean :
	$(RM) *.o $(PROJ)